In [1]:
import numpy as np                    
import pandas as pd 
import matplotlib.pyplot as plt                        

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation="linear"))

e:\Anaconda\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary() 

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[1.0936519 , 0.5941706 ],
        [0.93684995, 0.86252725]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.09129918],
        [-0.9151996 ]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [8]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=10,verbose=1,batch_size=1)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 233.1367
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 227.5432
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 222.0453
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 216.4607
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 211.1160
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 205.8179
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 200.9138
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 195.5046
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 190.6858
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 185.6529


In [9]:
model.get_weights()

[array([[1.1345308 , 0.55497575],
        [0.97651595, 0.82449436]], dtype=float32),
 array([ 0.04073426, -0.03905766], dtype=float32),
 array([[ 0.1306566 ],
        [-0.87646097]], dtype=float32),
 array([0.03924026], dtype=float32)]